"""add instant retail operations

Revision ID: 2fce55de2167
Revises: 0004_demo_index_metadata
Create Date: 2026-08-07 19:13:20.526530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fce55de2167'
down_revision: Union[str, Sequence[str], None] = '0004_demo_index_metadata'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commerce_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=100), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_row_count', sa.Integer(), nullable=False),
    sa.Column('basket_count', sa.Integer(), nullable=False),
    sa.Column('product_count', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users_v2.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'fingerprint', name='uq_commerce_import_owner_fingerprint')
    )
    op.create_index(op.f('ix_commerce_imports_owner_id'), 'commerce_imports', ['owner_id'], unique=False)
    op.create_table('commerce_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('data_origin', sa.String(length=20), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users_v2.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'source_key', name='uq_commerce_product_owner_key')
    )
    op.create_index(op.f('ix_commerce_products_name'), 'commerce_products', ['name'], unique=False)
    op.create_index(op.f('ix_commerce_products_owner_id'), 'commerce_products', ['owner_id'], unique=False)
    op.create_table('merchant_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('business_type', sa.String(length=50), nullable=False),
    sa.Column('store_count', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users_v2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_profiles_owner_id'), 'merchant_profiles', ['owner_id'], unique=True)
    op.create_table('commerce_association_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('antecedent_product_id', sa.Integer(), nullable=False),
    sa.Column('consequent_product_id', sa.Integer(), nullable=False),
    sa.Column('cooccurrence_count', sa.Integer(), nullable=False),
    sa.Column('support', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('lift', sa.Float(), nullable=False),
    sa.Column('min_count', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['antecedent_product_id'], ['commerce_products.id'], ),
    sa.ForeignKeyConstraint(['consequent_product_id'], ['commerce_products.id'], ),
    sa.ForeignKeyConstraint(['import_id'], ['commerce_imports.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users_v2.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_id', 'antecedent_product_id', 'consequent_product_id', name='uq_commerce_rule_pair')
    )
    op.create_index(op.f('ix_commerce_association_rules_import_id'), 'commerce_association_rules', ['import_id'], unique=False)
    op.create_index(op.f('ix_commerce_association_rules_lift'), 'commerce_association_rules', ['lift'], unique=False)
    op.create_index(op.f('ix_commerce_association_rules_owner_id'), 'commerce_association_rules', ['owner_id'], unique=False)
    op.create_table('commerce_baskets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('source_basket_key', sa.String(length=100), nullable=False),
    sa.Column('ordered_at', sa.DateTime(), nullable=True),
    sa.Column('store_key', sa.String(length=50), nullable=True),
    sa.Column('channel', sa.String(length=30), nullable=True),
    sa.Column('data_origin', sa.String(length=20), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['commerce_imports.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users_v2.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_id', 'source_basket_key', name='uq_commerce_basket_import_key')
    )
    op.create_index(op.f('ix_commerce_baskets_import_id'), 'commerce_baskets', ['import_id'], unique=False)
    op.create_index(op.f('ix_commerce_baskets_owner_id'), 'commerce_baskets', ['owner_id'], unique=False)
    op.create_table('commerce_basket_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('basket_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('source_row_key', sa.String(length=50), nullable=False),
    sa.Column('data_origin', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['basket_id'], ['commerce_baskets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['commerce_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('basket_id', 'source_row_key', name='uq_commerce_item_basket_row')
    )
    op.create_index(op.f('ix_commerce_basket_items_basket_id'), 'commerce_basket_items', ['basket_id'], unique=False)
    op.create_index(op.f('ix_commerce_basket_items_product_id'), 'commerce_basket_items', ['product_id'], unique=False)
    op.create_table('commerce_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users_v2.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['commerce_association_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commerce_campaigns_owner_id'), 'commerce_campaigns', ['owner_id'], unique=False)
    op.create_table('commerce_campaign_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('copy', sa.Text(), nullable=False),
    sa.Column('rule_snapshot_json', sa.Text(), nullable=False),
    sa.Column('knowledge_document_id', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users_v2.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['commerce_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_document_id'], ['knowledge_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'version', name='uq_campaign_version')
    )
    op.create_index(op.f('ix_commerce_campaign_versions_campaign_id'), 'commerce_campaign_versions', ['campaign_id'], unique=False)
    op.create_table('evaluation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('campaign_version_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('config_snapshot_json', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_version_id'], ['commerce_campaign_versions.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['evaluation_datasets.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users_v2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_runs_dataset_id'), 'evaluation_runs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_owner_id'), 'evaluation_runs', ['owner_id'], unique=False)
    op.create_table('operation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('event_key', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('campaign_version_id', sa.Integer(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('data_origin', sa.String(length=20), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_version_id'], ['commerce_campaign_versions.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users_v2.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'event_key', name='uq_operation_event_owner_key')
    )
    op.create_index(op.f('ix_operation_events_event_type'), 'operation_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_operation_events_occurred_at'), 'operation_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_operation_events_owner_id'), 'operation_events', ['owner_id'], unique=False)
    op.create_table('evaluation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('expected_point_score', sa.Integer(), nullable=False),
    sa.Column('citation_correct', sa.Boolean(), nullable=False),
    sa.Column('refusal_correct', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('evidence_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_cases.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'case_id', name='uq_evaluation_result_run_case')
    )
    op.create_index(op.f('ix_evaluation_results_case_id'), 'evaluation_results', ['case_id'], unique=False)
    op.create_index(op.f('ix_evaluation_results_run_id'), 'evaluation_results', ['run_id'], unique=False)
    op.create_table('optimization_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('target_metric', sa.String(length=100), nullable=True),
    sa.Column('change_version', sa.String(length=100), nullable=True),
    sa.Column('verification_run_id', sa.Integer(), nullable=True),
    sa.Column('before_evidence_json', sa.Text(), nullable=False),
    sa.Column('after_evidence_json', sa.Text(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users_v2.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users_v2.id'], ),
    sa.ForeignKeyConstraint(['verification_run_id'], ['evaluation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_tasks_owner_id'), 'optimization_tasks', ['owner_id'], unique=False)
    op.create_index(op.f('ix_optimization_tasks_status'), 'optimization_tasks', ['status'], unique=False)
    op.create_table('evaluation_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('failure_category', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['evaluation_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users_v2.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('result_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation_labels')
    op.drop_index(op.f('ix_optimization_tasks_status'), table_name='optimization_tasks')
    op.drop_index(op.f('ix_optimization_tasks_owner_id'), table_name='optimization_tasks')
    op.drop_table('optimization_tasks')
    op.drop_index(op.f('ix_evaluation_results_run_id'), table_name='evaluation_results')
    op.drop_index(op.f('ix_evaluation_results_case_id'), table_name='evaluation_results')
    op.drop_table('evaluation_results')
    op.drop_index(op.f('ix_operation_events_owner_id'), table_name='operation_events')
    op.drop_index(op.f('ix_operation_events_occurred_at'), table_name='operation_events')
    op.drop_index(op.f('ix_operation_events_event_type'), table_name='operation_events')
    op.drop_table('operation_events')
    op.drop_index(op.f('ix_evaluation_runs_owner_id'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_dataset_id'), table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_index(op.f('ix_commerce_campaign_versions_campaign_id'), table_name='commerce_campaign_versions')
    op.drop_table('commerce_campaign_versions')
    op.drop_index(op.f('ix_commerce_campaigns_owner_id'), table_name='commerce_campaigns')
    op.drop_table('commerce_campaigns')
    op.drop_index(op.f('ix_commerce_basket_items_product_id'), table_name='commerce_basket_items')
    op.drop_index(op.f('ix_commerce_basket_items_basket_id'), table_name='commerce_basket_items')
    op.drop_table('commerce_basket_items')
    op.drop_index(op.f('ix_commerce_baskets_owner_id'), table_name='commerce_baskets')
    op.drop_index(op.f('ix_commerce_baskets_import_id'), table_name='commerce_baskets')
    op.drop_table('commerce_baskets')
    op.drop_index(op.f('ix_commerce_association_rules_owner_id'), table_name='commerce_association_rules')
    op.drop_index(op.f('ix_commerce_association_rules_lift'), table_name='commerce_association_rules')
    op.drop_index(op.f('ix_commerce_association_rules_import_id'), table_name='commerce_association_rules')
    op.drop_table('commerce_association_rules')
    op.drop_index(op.f('ix_merchant_profiles_owner_id'), table_name='merchant_profiles')
    op.drop_table('merchant_profiles')
    op.drop_index(op.f('ix_commerce_products_owner_id'), table_name='commerce_products')
    op.drop_index(op.f('ix_commerce_products_name'), table_name='commerce_products')
    op.drop_table('commerce_products')
    op.drop_index(op.f('ix_commerce_imports_owner_id'), table_name='commerce_imports')
    op.drop_table('commerce_imports')
    # ### end Alembic commands ###
